### ISSUE TITLE
Running 'index.js' on glitch.com

### ISSUE THREAD

**Issue by LeoDoesThings** [DougTy/concord#116]
I'm trying to run concord on _glitch.com_ which is a web hosting website but can be used to run node applications.

I am stuck on running _index.js_ since I am an idiot and don't know how to do that from gltich.com. I can say that there is a console and debugger available for use.

pls help me im dumb

**Comment by DougTy** [comment]
Sorry, but I really have no experience with glitch.com, so I can't really help you out there.

My best guess is that you can't actually input raw commands onto that site, so if there's any kind of "run script" button, try that to start the bot.

If you're looking for free hosting for the bot, I have tested heroku to work well with concord. Check out the wiki for detailed instructions on how to get that working.

**Comment by LeoDoesThings** [comment]
Alright I managed to execute it somehow but now it says 

"Starting inspector on localhost:9200 failed: address not available"

**Comment by LeoDoesThings** [comment]
And now it has added

"process exited with code 12, restarting..."

to the console and is repeating that and the localhost fail message

**Comment by DougTy** [comment]
`Starting inspector on localhost:9200 failed: address not available` sounds like an error with the host, as it's not an error concord would throw nor have I seen it before. I don't know what it could mean.

I've never used glitch before so I really can't help you with it at all. I'm completely clueless. I know heroku works, though I haven't tested it very thoroughly. While you're of course free to run the bot for your own personal use, and while I'm happy to point people in the right direction, I can't really give detailed support for this kind of thing. Sorry.

If you're interested, I'll probably be hosting the bot for public use sometime later this year, so you can just add it to your server without having to set it up and host it yourself. I can't say exactly when as I have quite a few other things in the pipeline right now, but let me know if you'd be interested in that & I can try and speed it along.

**Comment by LeoDoesThings** [comment]
Alright thanks.
