### ISSUE TITLE
Use fs.readFileSync instead of require for show_playlist_count

### ISSUE THREAD

**Issue by DougTy** [DougTy/concord#130]
require is cached and doesn't refresh when file changes -- use fs.readFileSync instead

**Comment by linkjay** [comment]
Turns out you can also access the cache with `process.cache`, and more specifically, you can remove from the cache with this code:

`delete require.cache[require.resolve(module)]`

So I think it's worth comparing readFile then JSON.parse vs. require performance.

**Comment by DougTy** [comment]
For variable data I'd rather use fs.readFileSync than muck about with the require cache, as I consider that to be bad practice for this use case. This will also aide in the future as I replace all sync operations with async: #83

**Comment by linkjay** [comment]
fixed in #131
